#Video
hwdec=nvdec-copy
hwdec-codecs=all
hr-seek-framedrop=no
no-resume-playback
profile=gpu-hq
gpu-api=vulkan
scale=ewa_lanczossharp
scale-blur=0.981251
cscale=ewa_lanczossharp
target-trc=srgb
gamma-factor=1.1

#subs
alang = 'jpn,jp,eng,en'
slang = 'eng,en,enUS' # enUS for Crunchyroll.
sub-auto=fuzzy

#deband
deband=yes # Default values are 1:64:16:48
deband-iterations=4 # Range 1-16. Higher = better quality but more GPU usage. >5 is redundant.
deband-threshold=48 # Range 0-4096. Deband strength.
deband-range=16 # Range 1-64. Range of deband. Too high may destroy details.
deband-grain=4 # Range 0-4096. Inject grain to cover up bad banding, higher value needed for poor sources.

#
volume=100 # Set volume to 100% on startup.
volume-max=125 # Set player max vol to 100%.
