# i3blocks configuration file
#
# The i3blocks man page describes the usage of the binary,
# and its website describes the configuration:
#
#     https://vivien.github.io/i3blocks


# Global properties
#separator=false
#separator_block_width=30

color=#DDDDDD
separator=false
separator_block_width=9

#[greetings]
#color=#db2c2c
#command=echo "$USER@$HOSTNAME"
#interval=once

[backlight]
command= ~/.local/bin/brightness
interval=60
signal=10

[volume]
command= ~/.local/bin/volume
interval=60
signal=10

[temp]
command= ~/.local/bin/temp
interval=1

[battery]
command= ~/.local/bin/battery
interval=60

[time]
command= ~/.local/bin/datey
interval=60
