# i3blocks configuration file
#
# The i3blocks man page describes the usage of the binary,
# and its website describes the configuration:
#
#     https://vivien.github.io/i3blocks


# Global properties
separator=true
separator_block_width=15

#[greetings]
#color=#f12711
#command=echo "$USER@$HOSTNAME"
#interval=once

[backlight]
command= ~/.local/bin/brightness
interval=60
signal=10

[volume]
command= ~/.local/bin/volume
interval=60
signal=10

[temp]
command= ~/.local/bin/temp
interval=1

[battery]
command= ~/.local/bin/battery
interval=60

[time]
label=🕓 
command=date '+%A %d %B %Y %I:%M %p'
interval=60
