#Video
hwdec=auto-copy
hwdec-codecs=all
hr-seek-framedrop=no
no-resume-playback
profile=gpu-hq
gpu-api=vulkan

#subs
alang = 'jpn,jp,eng,en'
slang = 'eng,en,enUS' # enUS for Crunchyroll.

# Audio
#Default volume of the player
volume=100 

#Max volume of the player
volume-max=200


#network - youtube-dl
ytdl-format=bestvideo[height<=?1080]+bestaudio/best # Set max streaming quality as 1080p.
# Default demuxer is 150/75 MB, note that this uses RAM so set a reasonable amount.
demuxer-max-bytes=150000000 # 150MB, Max pre-load for network streams (1 MiB = 1048576 Bytes).
demuxer-max-back-bytes=75000000 # 75MB, Max loaded video kept after playback.
force-seekable=yes # Force stream to be seekable even if disabled.
sub-auto=fuzzy

#sceenshot
screenshot-format=png
screenshot-high-bit-depth=yes
screenshot-png-compression=7 # Setting too high may lag the PC on weaker systems. Recommend 3 (weak systems) or 7.
screenshot-directory="~/Pictures/"

#deband
deband=yes # Default values are 1:64:16:48
deband-iterations=4 # Range 1-16. Higher = better quality but more GPU usage. >5 is redundant.
deband-threshold=62 # Range 0-4096. Deband strength.
deband-range=18 # Range 1-64. Range of deband. Too high may destroy details.
deband-grain=0 # Range 0-4096. Inject grain to cover up bad banding, higher value needed for poor sources.

#
volume=100 # Set volume to 100% on startup.
volume-max=125 # Set player max vol to 100%.



# c Down
glsl-shader="/etc/mpv/sdown.glsl"
dscale=ewa_lanczos
linear-downscaling=no
fbo-format=rgba16hf

# c scale
glsl-shader="/etc/mpv/kb.glsl"
cscale=mitchell
fbo-format=rgba16hf


#internal scales
glsl-shader="/etc/mpv/sssr.glsl"
scale=ewa_lanczossharp






